version: '3'
services: 
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'laratest_db'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_PASSWORD: ""
  app:
    image: qasim683/laravel-app:1.0.1
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
