name: Deployment Workflow
on:
  push:
    branches:
      - master
jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing Deployment
      uses: appleboy/ssh-action@master
      with:
        host: dev-server.us-central1-a.c.weighty-nation-272311.internal
        username: qasim
        key: ${{ secrets.OMG_SECRET }}
        port: 22
        script: |
          cd final_test
          git pull origin master
          git status















   
          