name: Docker build for Laravel

on:
  push:
    branches:
      - master

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Prepare environment for Dev build
      run: |
        cp env.dev .env
    - name: Docker build
      run: |
        docker build . -t qasim683/laravel-app:1.0.2
    - name: Docker push images
      run: |
        docker push docker.io/qasim683/laravel-app:1.0.2
  Deploy-job:
    needs: [build-job]
    if: success()
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing Deployment
      uses: appleboy/ssh-action@master
      with:
        host: 130.211.208.37 
        username: qasim
        key: ${{ secrets.OMG_SECRET }}
        port: 22
        script: |
          
          git clone https://github.com/qasim683/final_test.git
          cd final_test
          docker-compose up -d