name: Docker build for Laravel

on:
  push:
    branches:
      - dev

jobs:
  
  Deploy-job:
    
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing Deployment
      uses: appleboy/ssh-action@master
      with:
        host: 34.121.38.48
        username: qasim
        key: ${{ secrets.OMG_SECRET }}
        port: 22
        script: |
          git clone https://github.com/qasim683/final_test.git
          cd final_test
          git pull origin dev
          mv env.dev .env
          cd dev-docker
          
          docker-compose -f docker-compose-dev.yaml up --build -d