name: Docker build for Laravel

on:
  push:
    branches:
      - dev-test

jobs:

  Deploy-job:

    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing Deployment
      uses: appleboy/ssh-action@master
      with:
        host: 130.211.208.37 
        username: qasim
        key: ${{ secrets.OMG_SECRET }}
        port: 22
        script: |
          
          git clone https://github.com/qasim683/final_test.git
          
          cd final_test
          git pull origin dev-test
          cp env.dev .env
          docker-compose -f docker-compose-dev.yaml up --build -d
          