name: Docker build for Laravel

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker build
      runs: |
        docker build ./.docker -t qasim683/laravel-app:1.0.0