name: Docker build for Laravel

on:
  push:
    branches:
      - master

jobs:
  laravel-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
    - name: Docker build
      run: |
        docker build . -t qasim683/laravel-app:1.0.0
    - name: Docker push images
      run: |
        docker push docker.io/qasim683/laravel-app:1.0.0
  laravel-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Add SSH Credentials
      uses: qasim683/ssh-key-action@master
      with:
        host: example.qbitflame.com
        username: qasim
        key: {{ secrets.OMG_SECRET }}
        port: 22
        script: |
          git pull origin master
          git status

    # - name: Deploy to Staging
    #   uses: qasim683/final_test@master
    #   with:
    #     deploy_targets: 'server-1.example.com, server-2.example.com' # required, comma separated list of servers to deploy to.

    #     ssh_user: 'root' # optional, user to connect to deploy targets with. Defaults to 'root'
    #     compose_file: 'docker-compose.yml' # optional, path/filename of your docker-compose file. Defaults to 'docker-compose.yml'
    #     validate_container: 'app' # optional, validate that the given container name is running. Otherwise, throw an error. Defaults to 'app' 