name: Docker build for Laravel

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
    - name: Docker build
      run: |
        docker build . -t qasim683/laravel-app:1.0.0
    - name: Docker push images
      run: |
        docker push docker.io/qasim683/laravel-app:1.0.0
        