name: Docker build for Laravel

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: check direc
      run: |
        ls
    - name: docker build
      run: |
        docker build ./.docker -t qasim683/laravel-app:1.0.0