# on: push
# name: CI
# jobs:
#   phpunit:
#     runs-on: ubuntu-latest
#     container:
#       image: qasim683/base-image-laravel:v1

#     services:
#       mysql:
#         image: mysql:5.7
#         env:
#           MYSQL_DATABASE: 'laratest_db'
#           MYSQL_ALLOW_EMPTY_PASSWORD: 1
#           MYSQL_PASSWORD: ""
#         ports:
#           - 33306:3306
#         options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

#     steps:
#     - uses: actions/checkout@v1
#       with:
#         fetch-depth: 1

#     - name: Install composer dependencies
#       run: |
#         composer install --no-scripts

#     - name: Prepare Laravel Application
#       run: |
#         php artisan key:generate

#     - name: Run Testsuite
#       run: vendor/bin/phpunit tests/
on: push
name: CI
jobs:
build:
runs-on: ubuntu-latest
    
  steps:
    - uses: actions/checkout@v1 # may be actions/checkout@v2 now
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    - name: Build the tagged Docker image
      run: docker build ./docker/Dockerfile --file Dockerfile --tag qasim683/laravel-app:${{steps.vars.outputs.tag}}
    - name: Push the tagged Docker image
      run: docker push qasim683/laravel-app:${{steps.vars.outputs.tag}}
    
